### ISSUE TITLE
Delete all button on retries is not firing request

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/verk_web#63]
![](https://user-images.githubusercontent.com/8083/30693306-415583ac-9ecf-11e7-9a97-c024c1bc6e01.gif)

Initially reported here: https://github.com/edgurgel/verk_web/pull/62

**Comment by edgurgel** [comment]
@teamon I think this is now fixed. It was a mix of javascript errors + node modules issues.

**Comment by teamon** [comment]
I've just checked and the error still exists in 1940d4b06aad7265c5a39602095ba44f8c4bb6f9

**Comment by teamon** [comment]
It works, thanks!
